/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "SDA_DISPLAY_aliases.h"
#include "SDA_DISPLAY.h"
#include "SCL_DISPLAY_aliases.h"
#include "SCL_DISPLAY.h"
#include "I2C_DISPLAY.h"
#include "I2C_DISPLAY_PVT.h"
#include "ADC_POT.h"
#include "PIN_POT_aliases.h"
#include "PIN_POT.h"
#include "PIN_O_LED_aliases.h"
#include "PIN_O_LED.h"
#include "PIN_IR_aliases.h"
#include "PIN_IR.h"
#include "PWM_O_LED.h"
#include "CLOCK_O_LED.h"
#include "ISR_IR.h"
#include "PWM_BUZZER.h"
#include "PIN_BUZZER_aliases.h"
#include "PIN_BUZZER.h"
#include "CLK_BUZZER.h"
#include "CLK_ALARM.h"
#include "PWM_ALARM.h"
#include "PIN_ALARM_aliases.h"
#include "PIN_ALARM.h"
#include "ADC_POT_IRQ.h"
#include "ADC_POT_theACLK.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

